### DISCUSSION TITLE
[Enhancement] [table-v2] ElTableV2 add size、border feature like the traditional table component

### DISCUSSION THREAD

**Discussion by bug4j** [element-plus/element-plus#11759] [Feature Request]
Feature type: **`Enhancement`**

## Details

- Enhanced component name: `table-v2`

## Description

the default height of the table row is too big, and there is no attribute like 'size'、'condensed' or any other ways to change that.
please consider to add feature to do so, make the ElTableV2 component more like the ElTable component.

here are some feature that came to mine mind:
1. size
2. border
3. stripe
4. row-contextmenu event, header-contextmenu and other events.
5. column resizable
6. colmun slots
7. ...

### Additional comments

_(empty)_

**Comment by litt1e-p** [comment]
yes, `border` and `column resizable` is most needed

**Comment by lanrenbulan** [comment]
@kooriookami 这个需求能加上吗

**Reply by kooriookami** [reply]
需求合理，目前没有人负责这一块。Todo。

**Comment by snailwei** [comment]
`stripe` is urgently required, please!!!

The dirty workaround
```css
<style>
.ep-table-v2__row:nth-of-type(even) {
  background: rgba(128, 128, 128, 0.2);
}

.ep-table-v2__row:hover {
  background: rgba(128, 128, 128, 0.5);
}
</style>
```
