### DISCUSSION TITLE
[table] 可以不默认表头样式{"user-select":"none"}吗？选择表头文本并复制是一个常见的情况

### DISCUSSION THREAD

**Discussion by lovefqy** [element-plus/element-plus#12176] [Feature Request]
Feature type: **`Other`**

## Details

- Enhanced component name: `table`

## Description

可以不默认表头样式{"user-select":"none"}吗？选择表头文本并复制是一个常见的情况，这样就不需要额外定义类似样式覆盖为
```css
.el-table th.el-table__cell {
    user-select:text;
}
```

### Additional comments

_(empty)_
