### DISCUSSION TITLE
css prefix configuration

### DISCUSSION THREAD

**Discussion by Chris-Kin** [element-plus/element-plus#1401] [Ideas]
Block name has been extract as `$namespace` in `/packages/theme-chalk/src/mixins/config.scss`:
```scss
$namespace: 'el';
```
And it's used in `/packages/theme-chalk/src/mixins/mixins.scss`.

```scss
/* BEM
 -------------------------- */
@mixin b($block) {
  $B: $namespace+'-'+$block !global;

  .#{$B} {
    @content;
  }
}
```
I think this is a good embodiment of the idea of configuration. Making project more flexible and configurable!

But `$namespace` only be used in `mixins.scss`, what I think is that `$namespace` should be throughout all the style files(also include website-demo-style files).

For example, current `theme-chalk/src/alert.scss` file like this:
```scss
@include when(light) {
  .el-alert__closebtn {
    color: $--color-text-placeholder;
  }
}
.el-alert-fade-enter,
.el-alert-fade-leave-active {
  opacity: 0;
}
```
In the code above, **el** equals with $namespace's real value `el`.

It should look more reasonable like this:
```scss
@include when(light) {
  .#{$namespace}-alert__closebtn {
    color: $--color-text-placeholder;
  }
}
.#{$namespace}-alert-fade-enter,
.#{$namespace}-alert-fade-leave-active {
  opacity: 0;
}
```
<hr />

If this is indeed necessary, I'm glad to submit a PR.
