### DISCUSSION TITLE
Is it possible to interact with the background form/window when using draggble?

### DISCUSSION THREAD

**Discussion by Alex-Shchukarev** [element-plus/element-plus#15978] [Q&A]
Check out the example in the video. Is there any way to implement switching between forms\windows in the current version of the library 2.5.4? The dialog box and the background form can be active alternately. When the dialog box is active, you can move it. When the background form is active, you can interact with it (for example, click buttons on it), but the dialog box is inactive and cannot be moved.

https://github.com/element-plus/element-plus/assets/78414390/733536b8-5971-4c42-b6ef-2d2c832a4140

**Comment by kooriookami** [comment]
You can set:
```css
.el-overlay-dialog { pointer-events: none; }
.el-dialog { pointer-events: auto; }
```
