### DISCUSSION TITLE
[Enhancement] 诸如el-checkbox-button的hover效果希望可以用any-hover进行增强，避免移动端出现hover效果导致需要手动修改css

### DISCUSSION THREAD

**Discussion by jackjtr** [element-plus/element-plus#17707] [Feature Request]
Feature type: **`Enhancement`**

## Details

- Enhanced component name: `All`

## Description

诸如el-checkbox-button的hover效果希望可以用any-hover进行增强，避免移动端出现hover效果导致需要手动修改css

```css
@media (any-hover: hover) {
  a:hover {
    background: yellow;
  }
}
```

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/any-hover

### Additional comments

_(empty)_
