### DISCUSSION TITLE
How to remove popper default offset?

### DISCUSSION THREAD

**Discussion by ghiscoding** [element-plus/element-plus#6039] [Q&A]
Hello, I'm new to the lib and so far it is an awesome library. I just wish to remove all the popper offset for all components to match our styling design guideline. The offset might be coming from this code of the lib
https://github.com/element-plus/element-plus/blob/a995d4487bb4f5b8575f8fd7a29148555785c173/packages/components/popper/src/popper.ts#L44-L47

is there a way to override this? 

For example, instead of 
![image](https://user-images.githubusercontent.com/643976/153911175-52082322-b922-45e4-9bf3-0bb0673b8fa7.png)

**I want this**
![image](https://user-images.githubusercontent.com/643976/153910638-c7ab9f5e-9117-469e-9856-aa0e30400354.png)

for now I'm using this styling but, that is probably not the best way of doing it!?

```scss
<style lang="scss">
.el-menu--horizontal {
  margin-top: -6px;
}
.el-menu--popup-right-start {
  margin-left: -6px;
}
</style>
```
