### DISCUSSION TITLE
关于运行时多主题切换的探讨与实现

### DISCUSSION THREAD

**Discussion by hooray** [element-plus/element-plus#7955] [Ideas]
我有这样一个需求，就是运行时的多主题切换。

由于 element-plus 并不支持在编译时就生成多套主题的样式（或许有方案），所以我只能在运行时去动态覆盖生成的 css var 属性。

但目前遇到一个比较麻烦的问题就是，比如我动态覆盖 `--el-color-primary` 后，`--el-color-primary-light-3` `--el-color-primary-light-5` ... 这一系列和 `--el-color-primary` 有关联的属性并没有变化。因为它们是在编译时通过 scss 的函数计算出来的，而编译生成 css var 后之间就没有直接关系了，所以通过覆盖 css var 时，需要将每一个属性都单独进行覆盖。而我希望能做到只修改覆盖一处，该颜色相关的色彩阶梯都能一并自动处理，就像很多组件背景色的 css var 是依赖 `--el-bg-color` 和 `--el-bg-color-page` ，我只需要覆盖 `--el-bg-color` 和 `--el-bg-color-page` ，这些组件的 css var 都一并生效了，不需要我修改覆盖太多 css var

于是我想到的第一个方案是，用 `rgb` 的半透明来实现色彩阶梯，例如生成的 css var 可以是这样：

```css
:root {
  --el-color-primary-value: 64 158 255;
  --el-color-primary: rgb(var(--el-color-primary-value));
  --el-color-primary-light-3: rgb(var(--el-color-primary-value) / 0.9);
  --el-color-primary-light-5: rgb(var(--el-color-primary-value) / 0.7);
  ...
}
```

但这又带来一个问题，半透明的效果应用在背景色上显然有点不合适，例如 el-button 这类组件，如果底色不是纯色，半透明的效果会影响视觉观感。

于是我思考其实可以将 `--el-color-primary-value` 进一步拆分成 `--el-color-primary-value-r` `--el-color-primary-value-g` `--el-color-primary-value-b` 保存，因为我将默认生成的 `--el-color-primary` 转成 rgb 后发现，色彩阶梯实际上是有一定规律的：

```css
:root {
  --el-color-primary: #409eff;
  --el-color-primary-light-3: #79bbff;
  --el-color-primary-light-5: #a0cfff;
  --el-color-primary-light-7: #c6e2ff;
  --el-color-primary-light-8: #d9ecff;
  --el-color-primary-light-9: #ecf5ff;
  --el-color-primary-dark-2: #337ecc;
}

/* 转成 rgb 后 */
:root {
  --el-color-primary: rgb(64 158 255);
  --el-color-primary-light-3: rgb(121 187 255);
                               /* +39 +20 +0 */
  --el-color-primary-light-5: rgb(160 207 255);
                               /* +38 +19 +0 */
  --el-color-primary-light-7: rgb(198 226 255);
                               /* +19 +10 +0 */
  --el-color-primary-light-8: rgb(217 236 255);
                               /* +19 +9  +0 */
  --el-color-primary-light-9: rgb(236 245 255);
  --el-color-primary-dark-2: rgb(51 126 204);
}
```

因为生成的 css var 并没有 `--el-color-primary-light-1` `--el-color-primary-light-2` `--el-color-primary-light-4` `--el-color-primary-light-6` ，如果我把这4个阶梯色值补上，并按照观察出的规律（即`每个相邻的色值阶梯：red+19或20，green+9或10` ），大致应该是这样：

```css
:root {
  --el-color-primary:         rgb(64 158 255);
                               /* +19 +10 +0 */
  --el-color-primary-light-1: rgb(83 168 255);
                               /* +19 +10 +0 */
  --el-color-primary-light-2: rgb(102 178 255);
                               /* +19 +9  +0 */
  --el-color-primary-light-3: rgb(121 187 255);
                               /* +19 +10 +0 */
  --el-color-primary-light-4: rgb(140 197 255);
                               /* +20 +10 +0 */
  --el-color-primary-light-5: rgb(160 207 255);
                               /* +19 +10 +0 */
  --el-color-primary-light-6: rgb(179 217 255);
                               /* +19 +9  +0 */
  --el-color-primary-light-7: rgb(198 226 255);
                               /* +19 +10 +0 */
  --el-color-primary-light-8: rgb(217 236 255);
                               /* +19 +9  +0 */
  --el-color-primary-light-9: rgb(236 245 255);
}
```

`--el-color-primary-dark-2` 比较特殊，因为就只有一个，也分析不出递减规律，就直接拿它和 `--el-color-primary` 相减取一个固定值吧

```css
:root {
  --el-color-primary:        rgb(64 158 255);
                             /* -13 -32 -41 */
  --el-color-primary-dark-2: rgb(51 126 204);
}
```

这样一顿分析后，似乎得到了我想要的结果，是否可以将 css var 生成成这样：

```css
:root {
  --el-color-primary-value-r: 64;
  --el-color-primary-value-g: 158;
  --el-color-primary-value-b: 255;
  --el-color-primary: rgb(var(--el-color-primary-value-r) var(--el-color-primary-value-g) var(--el-color-primary-value-b));
  --el-color-primary-light-3: rgb(calc(var(--el-color-primary-value-r) + 19 * 3) calc(var(--el-color-primary-value-g) + 10 * 3) var(--el-color-primary-value-b));
  --el-color-primary-light-5: rgb(calc(var(--el-color-primary-value-r) + 19 * 5) calc(var(--el-color-primary-value-g) + 10 * 5) var(--el-color-primary-value-b));
  --el-color-primary-light-7: rgb(calc(var(--el-color-primary-value-r) + 19 * 7) calc(var(--el-color-primary-value-g) + 10 * 7) var(--el-color-primary-value-b));
  --el-color-primary-light-8: rgb(calc(var(--el-color-primary-value-r) + 19 * 8) calc(var(--el-color-primary-value-g) + 10 * 8) var(--el-color-primary-value-b));
  --el-color-primary-light-9: rgb(calc(var(--el-color-primary-value-r) + 19 * 9) calc(var(--el-color-primary-value-g) + 10 * 9) var(--el-color-primary-value-b));
  --el-color-primary-dark-2: rgb(calc(var(--el-color-primary-value-r) - 13) calc(var(--el-color-primary-value-g) - 32) calc(var(--el-color-primary-value-b) - 41));
}
```

这样一来，实现运行时主题切换，就只需要覆盖 `--el-color-primary-value-r` `--el-color-primary-value-g` `--el-color-primary-value-b` 这 3 个色值即可，而无需关注色彩阶梯里的每个阶梯色的变化，会让主题切换变得轻松很多。

其它如 success / warning / danger 也同理。
