### DISCUSSION TITLE
El-Menu菜单背景颜色设置，namespace方式--bg-color怎么用？

### DISCUSSION THREAD

**Discussion by songxh2** [element-plus/element-plus#9895] [Q&A] [answered]
background-color | 菜单的背景颜色（十六进制格式）（已被废弃，使用--bg-color）

按照上面组件描述，我不想使用background-color属性设置背景颜色(已被废弃)，那--bg-color方式怎么用呢？

我用 `<el-menu style="--bg-color:red"  >...</el_menu>`也没有效果啊！
那位大神给个提示，不知道哪里出错了！

**Comment by songxh2** [comment, marked as answer]
结果使用`<el-menu style="--el-menu-bg-color:red" >...</el_menu>` 有效！！与文档描述不相符。

**Comment by chenxch** [comment]
这块文档可以完善一下哈

**Comment by TIUCSIB** [comment]
我今天也遇到这问题了，不过应该不是你这样理解的，文字颜色（十六进制格式）（已被废弃，使用--text-color）--text-color应该是让你声明一个css变量，从里面抽离出来。不直接在上面写text-color=“不直接写十六进制” 而是text-color=“var(--text-color)”
style里面就写例如el-menu（外面包裹的标签元素）{--text-color:'#xxxxx'}

**Comment by ye65432** [comment]
这样的！css变量覆盖掉element默认的值

element-variables.scss
`:root {
  --el-menu-hover-bg-color: #000;
  --el-menu-active-color: #fff;
  --el-menu-text-color: #fff;
  --el-menu-bg-color: pink;
}`

**Comment by xpbsm** [comment]
css 变量名有作用域，找到任意父元素，覆盖你需要修改的变量
```scss
& {
    --el-menu-text-color: #d7bbbb;
    --el-menu-hover-text-color: #d7bbbb;
    --el-menu-bg-color: #1b1da9;
    --el-menu-hover-bg-color: #378ae7;
    --el-menu-active-color: #ffffff;
  }
```
