### ISSUE TITLE
[steps] el-steps的标题无法改变位置

### ISSUE THREAD

**Issue by RocChuang** [element-plus/element-plus#10037]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.1.7`
- Browser / OS: `macOS`
- Build Tool: `Vite`

### Related Component

- `el-steps`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/steps.html)

### Steps to reproduce

el-steps的标题无法改变位置

### What is Expected?

el-steps的标题可以在上方或左侧

### What is actually happening?

el-steps的标题无法改变位置

### Additional comments

_(empty)_

**Comment by chenxch** [comment]
```css
.el-step.is-horizontal {
    display: inline-flex;
    flex-direction: column-reverse;
}
```
可以通过修改样式实现哦
