### ISSUE TITLE
[Style] [scrollbar] el-scrollbar占用的高度与显示的高度不一致

### ISSUE THREAD

**Issue by hhucqian** [element-plus/element-plus#12752]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.32`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-scrollbar`

### Reproduction Link

[Link]()

### Steps to reproduce

我在使用el-scrollbar的时候通过height属性设置了高度，但是发现el-scrollbar实际占用高度会比显示的高度多一点。经过调试发现是由于el-scrollbar的默认样式导致的：
```css
.el-scrollbar {
    overflow: hidden;
    position: relative;
    height: 100%;
}
```
所以我在代码里面手动添加的额外的样式，覆盖掉默认样式的height属性：
```css
.el-scrollbar{
    height: auto;
}
```
el-scrollbar实际占用的高度就和显示内容的高度一致了。

我不清楚这个默认样式为什么要这么设置，至少在我的使用场景里面他不是特别合理，是否可以去掉.el-scrollbar样式中的`height: 100%;`内容。

### What is Expected?

null

### What is actually happening?

null

### Additional comments

_(empty)_
