### ISSUE TITLE
[Style] [dropdown] Dropdown 按钮形态下，鼠标移出不会变为原来的颜色

### ISSUE THREAD

**Issue by WangJincheng4869** [element-plus/element-plus#13702]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35`
- Build Tool: `Vite`

### Related Component

- `el-dropdown`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/dropdown.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)

### Steps to reproduce

1、点击一下按钮
2、点击空白区域让其颜色变为正常
3、鼠标移入颜色转变
4、鼠标移出颜色不会恢复

### What is Expected?

颜色恢复为正常状态

### What is actually happening?

颜色无法恢复

### Additional comments

_(empty)_

![动画](https://github.com/element-plus/element-plus/assets/41162158/f4b23351-237d-4926-9241-7d80f88549db)

**Comment by enhengenheng-hubowen** [comment]
可以使用@mousedown="$event => $event.preventDefault()"来暂时解决这个需求,饿了么不失焦是因为他要考虑网站无障碍相关问题.

**Comment by enhengenheng-hubowen** [comment]
如果不知道具体怎么操作可以看这.https://juejin.cn/post/7230348908383027259

**Comment by tolking** [comment]
这属于 Button 的 focus 样式，你可以自己定义相关样式

```css
.el-button:focus {
  color: var(--el-button-text-color);
  border-color: var(--el-button-border-color);
  background-color: var(--el-button-bg-color);
}
```
