### ISSUE TITLE
[Bug Report] tabs component has a strange style

### ISSUE THREAD

**Issue by Chris-Kin** [element-plus/element-plus#1391]
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
macOS/chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/yummy/pen/xxRxqRr?editors=1011

### Steps to reproduce
open reproduction link
switch active tab

### What is Expected?
Tabs should not get a outline whe ElMessageBox is closed.

### What is actually happening?
There is outline around tab.

**Comment by Chris-Kin** [comment]
![tab](https://user-images.githubusercontent.com/10802869/106273928-6972fc00-626e-11eb-9787-33b4bd07262b.png)


```scss
&:focus.is-active.is-focus:not(:active) {
  box-shadow: 0 0 2px 2px $--color-primary inset;
  border-radius: 3px;
}
```

This problem is caused by the code above. I'm not sure whether tabs should have the focus state style.
