### ISSUE TITLE
[Feature Request] Do you guys consider using native scrollbar with customized style instead of realizing a new one?

### ISSUE THREAD

**Issue by panjiangyi** [element-plus/element-plus#1442]
### Existing Component
No

### Component Name
scrollbar

### Description
We can control the scroll bar's appearance by js, little code with the same functionality as how Element-UI 2.0 did.

code is blow:

```css
.fake-el-scrollbar {
    --scrollbar-opacity: rgba(144, 147, 153, 0.3);

    &::-webkit-scrollbar {
        width: 6px;
    }
    &::-webkit-scrollbar-track {
        background-color: transparent;
        border-color: transparent;
    }

    &::-webkit-scrollbar-thumb {
        background-color: var(--scrollbar-opacity);
        box-shadow: unset;
    }
}

```
```ts
/*
 * 需要配合css使用 
 */
export default function FakeElScrollbar() {
    let target: HTMLElement | null = null;
    const min = 0;
    const max = 0.3;
    let enterInterverId: number;
    let leaveInterverId: number;
    const durationTime = 120;
    const frameTime = 12;
    const moveValue = (max - min) / (durationTime / frameTime)


    function mouseEnter() {
        clearInterval(enterInterverId);
        clearInterval(leaveInterverId);
        let i = min;
        enterInterverId = window.setInterval(() => {
            if (i > max) {
                i = max;
                clearInterval(enterInterverId);
            }
            target?.style.setProperty("--scrollbar-opacity", `rgba(144, 147, 153, ${i})`);
            i = i + moveValue;
        }, frameTime);
    }


    function mouseLeave() {
        clearInterval(enterInterverId);
        clearInterval(leaveInterverId);
        let i = 0.3;
        leaveInterverId = window.setInterval(() => {
            if (i < min) {
                i = min;
                clearInterval(leaveInterverId);
            }
            target?.style.setProperty("--scrollbar-opacity", `rgba(144, 147, 153, ${i})`);
            i = i - moveValue;
        }, frameTime);
    }

    return {
        enpower(wanted: HTMLElement) {
            target = wanted;
            target.classList.add("fake-el-scrollbar")
            target.addEventListener("mouseenter", mouseEnter);
            target.addEventListener("mouseleave", mouseLeave);
        },

        clear() {
            target?.removeEventListener("mouseenter", mouseEnter);
            target?.removeEventListener("mouseleave", mouseLeave);
            target = null;
        }
    }
}
```
