### ISSUE TITLE
[Component] [table] Element Plus:2.5.0表格数据超过一页打印页，表格头在上一页，表格内容跑下一页，tr会从中间断开

### ISSUE THREAD

**Issue by 992076178** [element-plus/element-plus#15454]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.5.0`
- Browser / OS: `chrome最新版本`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Link]( http://www.digitwater.com:6536/oa/pc/index.html#/HelloWorld)

### Steps to reproduce

使用el-table组件，数据超过一页打印页，点击打印，打印页显示问题

### What is Expected?

打印内容超过一页，表头跟表格内容在同一页，超过一页打印页，分页到下一页，tr内容不从中间断开

### What is actually happening?

Element Plus:2.5.0表格数据超过一页打印页，表格头在上一页，表格内容跑下一页，tr会从中间断开

### Additional comments

_(empty)_

![image](https://github.com/element-plus/element-plus/assets/87633945/ad695916-9735-462c-aa37-bb079f1f4c77)
![image](https://github.com/element-plus/element-plus/assets/87633945/37b9f383-05ec-40be-931b-a96f7fcb6d25)

**Comment by 992076178** [comment]
.el-scroller__view{ display:block !important}
试着改了下源码，加上面那个，表格内容上去了，但是最后几行显示不全，哥哥们可以看看，能力有限，只能解决到这里了

**Comment by qppq54s** [comment]
@992076178 
我尝试了下，删除表单头部，打印就正常了。应该是代码实现中，使用两个单独的table去创建头部和内容导致的问题。
不过我暂时也没找到解决方案。
但是我倒是想到另一个角度去解决。配置show-header为false，然后把表单的第一条数据插入为头部的内容。这样打印就正常了。

**Comment by hhhzzy** [comment]
打印时设置不分页
.el-table__header-wrapper{
    page-break-after: avoid;
}

**Comment by MisterBowie** [comment]
<img width="497" alt="image" src="https://github.com/element-plus/element-plus/assets/22372554/35be9c85-01ab-46ff-ad96-22ae65664f80">
我也是这样的

**Comment by up2gx** [comment]
try this

```css
@media print {
  tr {
    break-inside: avoid; // 表格项截断，设置 auto 为不截断
    page-break-inside: avoid;
  }
  .el-scrollbar__view {
    display: block !important;
  }
  .el-table__inner-wrapper {
    height: auto;
  }
 
  .el-scrollbar {
    height: auto !important;
  }
}
```
