### ISSUE TITLE
📌 Upgrade Changes 升级变化 (2.10.5)

### ISSUE THREAD

**Issue by kooriookami** [element-plus/element-plus#15834]
To make it easier for users to upgrade Element Plus, this issue will document the upgrade changes from version `2.5.0`. If you want to see the breaking changes of Element UI, please refer to #5658.

为了更好地方便用户升级 Element Plus，此 issue 将记录从 `2.5.0` 版本开始的升级变化。如果你想查看 Element UI 的不兼容变化，请参考 #5657.

**Comment by kooriookami** [comment]
## 2.5.0

_2024-01-10_

### Compatibility 兼容性
| ![Chrome](https://cdn.jsdelivr.net/npm/@browser-logos/chrome/chrome_32x32.png) <br> Chrome | ![IE](https://cdn.jsdelivr.net/npm/@browser-logos/edge/edge_32x32.png) <br> Edge | ![Firefox](https://cdn.jsdelivr.net/npm/@browser-logos/firefox/firefox_32x32.png) <br> Firefox | ![Safari](https://cdn.jsdelivr.net/npm/@browser-logos/safari/safari_32x32.png) <br> Safari |
| --- | --- | --- | --- |
| Chrome ≥ 85 | Edge ≥ 85 | Firefox ≥ 79 | Safari ≥ 14.1 |

### select & select-v2 #15352

The default width of components are 100%. Inline forms could cause the components width to be non-adaptive. It is recommended to manually set a fixed width style, for example:

组件默认宽度为100%，行内表单会造成组件宽度无法自适应。建议手动设置固定宽度样式，例如：

```scss
.el-form--inline {
  .el-form-item {
    & > .el-input, .el-cascader, .el-select, .el-date-editor, .el-autocomplete {
      width: 240px;
    }
  }
}
```
