### ISSUE TITLE
[Performance] [drawer] el-drawer动画卡顿，帧数低

### ISSUE THREAD

**Issue by qianjiachun** [element-plus/element-plus#17212]
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.5`
- Browser / OS: `Edge`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/drawer.html)

### Steps to reproduce

1. 使用edge浏览器
2. 关闭浏览器中【在可用时使用图形加速】设置
3. 打开官网的drawer链接，点击组件即可复现

### What is Expected?

无论打不打开【在可用时使用图形加速】，展开收缩动画都不卡顿

### What is actually happening?

动画明显卡顿

### Additional comments

在playground里是正常的，不知为何

已知的解决方案
1. 打开【在可用时使用图形加速】
2. F12切手机模拟
3. 换其他浏览器如Firefox等

**Comment by qianjiachun** [comment]
修改动画即可解决
``` scss
.el-drawer-fade-enter-from,.el-drawer-fade-leave-to {
  opacity: 1;
}
```
