### ISSUE TITLE
[Bug Report] element cann't work with tailwind css

### ISSUE THREAD

**Issue by initdc** [element-plus/element-plus#1804]
### Element Plus version
1.0.2-beta.39

### OS/Browsers version
macOS 10.15.7 / Chrome 88.0

### Vue version
3.0.5

### Reproduction Link
https://github.com/initdc/test-element-vite

### Steps to reproduce
add element-plus and tailwind css to project

### What is Expected?
el-button have no outline

### What is actually happening?
el-button has outline

![](https://github.com/initdc/pic/raw/master/element-plus.jpg)

**Comment by JeremyWuuuuu** [comment]
Seemed like you need to override css rules to get it workable though.

**Comment by rx2347** [comment]
Probably not a bug, I have a working example here: https://jsfiddle.net/8rjndhkv/6/ and have successfully used tailwind to style all kinds of components in production, even with using Webpack, PostCSS etc. 

Probably just importing the CSS files in the wrong order.

**Comment by initdc** [comment]
> Probably not a bug, I have a working example here: https://jsfiddle.net/yj4h7wtu/1/ and have successfully used tailwind to style all kinds of components in production, even with using Webpack, PostCSS etc.
> 
> Probably just importing the CSS files in the wrong order.

checkout this https://jsfiddle.net/x53ct7dz/ 

As I know ant-design can works with tailwind css, but not 100 percent, so I tried element, I prefer use element.

**Comment by rx2347** [comment]
> check this https://jsfiddle.net/x53ct7dz/

Maybe this is a missunderstanding? Why would Tailwind selectors work without importing it first?

**Comment by initdc** [comment]
That example is to show what a default style el-button should look like, tailwind css is not actually imported, and does not work.

I want to use tailwind css to adjust the size, color and other properties of the el-button, but as soon as I import tailwind, when the el-button gets focus, there will be outline.

Check the style [source code](https://github.com/element-plus/element-plus/blob/dev/packages/theme-chalk/src/button.scss) of the button and find that ```:focus``` is not set to ```outline: none```. I'm not sure that's right

> line 31 - 42
```scss
  &:hover,
  &:focus {
    color: $--color-primary;
    border-color: $--color-primary-light-7;
    background-color: $--color-primary-light-9;
  }

  &:active {
    color: mix($--color-black, $--color-primary, $--button-active-shade-percent);
    border-color: mix($--color-black, $--color-primary, $--button-active-shade-percent);
    outline: none;
  }
```
The problem might be the global style of tailwind css is overriding the style that el-button does not cover, and if users modifie the style by himself, it requires a very complicated operation and first understanding the principle.

So I think maybe it is a more elegant operation to define it from the source code.

**Comment by initdc** [comment]
I read the style [source code](https://github.com/vueComponent/ant-design-vue/blob/next/components/button/style/mixin.less) of the ant-design button, found this 
> line 207 - 237

```less
// Base styles of buttons
// --------------------------------------------------
.btn() {
  position: relative;
  display: inline-block;
  font-weight: @btn-font-weight;
  white-space: nowrap;
  text-align: center;
  background-image: none;
  border: @btn-border-width @btn-border-style transparent;
  box-shadow: @btn-shadow;
  cursor: pointer;
  transition: all 0.3s @ease-in-out;
  user-select: none;
  touch-action: manipulation;
  .button-size(@btn-height-base; @btn-padding-base; @font-size-base; @btn-border-radius-base);
  > .@{iconfont-css-prefix} {
    line-height: 1;
  }
  &,
  &:active,
  &:focus {
    outline: 0;
  }
  &:not([disabled]):hover {
    text-decoration: none;
  }
  &:not([disabled]):active {
    outline: 0;
    box-shadow: none;
  }
```

**Comment by rx2347** [comment]
@initdc Thanks for the clarification. Just remove the outline on focus with Tailwind if you don't like the default styles. Works quite fine, nothing complicated about it: https://jsfiddle.net/3xk168c7/30/

I don't think there is a bug here, can be closed IMO.

**Comment by initdc** [comment]
I have found two solutions

1. define the global style of ```button:focus```
```scss
button:focus {
    outline: 0;
}
```

2. add ```outline: none;``` to el-button ```:focus```
```scss
&:focus {
    color: $--color-primary;
    border-color: $--color-primary-light-7;
    background-color: $--color-primary-light-9;
    outline: none;
  }
```
I think el-button should add this property to protect the style from being changed by global properties
