### ISSUE TITLE
[Feature Request] Can you make default variable more default?

### ISSUE THREAD

**Issue by KawaiiZapic** [element-plus/element-plus#2482]
### Existing Component
Yes

### Component Name
Any component has a property that will convert to css prop

### Description
There are some default variable in compoments that will convert to css property, such as the `height` for `el-header`.  
But, the default variable will directly add to the style attribute on the element.
If I wanna to overwrite it (for responsive purpose, etc), __I MUST ADD__ A `!important`  __TO MY CODE__. If code is more complex, __ALL OF MY CODE WANNA CHANGE THIS PROPERTY NEED A `!important` TO TAKE EFFECT__.
For a simple example, a top bar will be 48px in small screen, 40px in tiny screen, 60px in other screen:  
```html
<el-header class="appbar"></el-header>
```
```css
.appbar {
    height: 60px;
}

@media screen and (max-height: 600px) {
    .appbar {
        height: 48px;
    }
}
@media screen and (max-height: 350px) {
    .appbar {
        height: 40px;
    }
}
```
The example code will not work, because there is a default style in the style attr of element and overwrite all code I write.  
I need change these to: 
```css 
.appbar {
    height: 60px!important;
}

@media screen and (max-height: 600px) {
    .appbar {
        height: 48px!important;
    }
}
@media screen and (max-height: 350px) {
    .appbar {
        height: 40px!important;
    }
}
```

This will make my code mess and may cause more problem.

Please directy save the default variable in css code, instead add these to style attr of element.

**Comment by msidolphin** [comment]
Because we want to supports height property.

**Comment by KawaiiZapic** [comment]
> Because we want to supports height property.

If a height property exist on the element, then just add it to `style` attribute.  
If there isn't a height property, just define it in css and leave `style` attribute blank.  

This is more flexable than add default variable to style attribute directly.

**Comment by JeremyWuuuuu** [comment]
> > Because we want to supports height property.
> 
> If a height property exist on the element, then just add it to `style` attribute.
> If there isn't a height property, just define it in css and leave `style` attribute blank.
> 
> This is more flexable than add default variable to style attribute directly.

I think you have just made your point, would you like to fix the issue? We would be more than happy to get the contribution from you. If you think otherwise I will add this to our backlog and fix it once we get time.

**Comment by KawaiiZapic** [comment]
> > > Because we want to supports height property.
> > 
> > 
> > If a height property exist on the element, then just add it to `style` attribute.
> > If there isn't a height property, just define it in css and leave `style` attribute blank.
> > This is more flexable than add default variable to style attribute directly.
> 
> @KawaiiZapic
> I think you have just made your point, would you like to fix the issue? We would be more than happy to get the contribution from you. If you think otherwise I will add this to our backlog and fix it once we get time.
> 
> Please let me know whether you were interested. 🙇

I'm sorry I'm really new to Vue, maybe I need more preparation for make contribution.

**Comment by msidolphin** [comment]
> > > > Because we want to supports height property.
> > > 
> > > 
> > > If a height property exist on the element, then just add it to `style` attribute.
> > > If there isn't a height property, just define it in css and leave `style` attribute blank.
> > > This is more flexable than add default variable to style attribute directly.
> > 
> > 
> > @KawaiiZapic
> > I think you have just made your point, would you like to fix the issue? We would be more than happy to get the contribution from you. If you think otherwise I will add this to our backlog and fix it once we get time.
> > Please let me know whether you were interested. 🙇
> 
> I'm sorry I'm really new to Vue, maybe I need more preparation for make contribution.

I'm afraid this is going to be a breaking change😂.

**Comment by JeremyWuuuuu** [comment]
We might be able to migrate this towards cssvar cc @YunYouJun WDTY?
Since we added inline style for the element so that in order to override the style we need to put `!important` after the overriding statement which could be violating some rules for some projects.

Proposal:
1. Update the `header.scss` with:
```scss

:root {
  --el-header-height: 60px; // default value
}
.el-header {
  height: var(--el-header-height);
}
```
2. In our `header.vue` we left the `height` as null say
```vue
<script>
export default { 
  props: {
    height: [Number, String],
    default: null,
  }
}
</script>

<template>
  <header class="el-header" :style="{ '--el-header-height': header }">
  </header>
</template>

```

**Comment by msidolphin** [comment]
> We might be able to migrate this towards cssvar cc @YunYouJun WDTY?
> Since we added inline style for the element so that in order to override the style we need to put `!important` after the overriding statement which could be violating some rules for some projects.
> 
> Proposal:
> 
> 1. Update the `header.scss` with:
> 
> ```css-scss
> :root {
>   --el-header-height: 60px; // default value
> }
> .el-header {
>   height: var(--el-header-height);
> }
> ```
> 
> 1. In our `header.vue` we left the `height` as null say
> 
> ```
> <script>
> export default { 
>   props: {
>     height: [Number, String],
>     default: null,
>   }
> }
> </script>
> 
> <template>
>   <header class="el-header" :style="{ '--el-header-height': header }">
>   </header>
> </template>
> ```

This way I can override the variables and still be compatible with the previous usage？

```css
@media screen and (max-height: 600px) {
    :root {
        --el-header-height: 48px;
    }
}
@media screen and (max-height: 350px) {
    :root {
        --el-header-height: 40px;
    }
}
```
