### ISSUE TITLE
[bug report] tooltip component style generation error

### ISSUE THREAD

**Issue by tolking** [element-plus/element-plus#2760]
### Element Plus version
1.0.2-beta.65

### OS/Browsers version
-

### Vue version
3.2.0-beta.6

### Reproduction Link
jsfiddle

### Steps to reproduce
升级到 `1.0.2-beta.65` 后，无法完成项目样式构建，排查是错误可能出现在

``` sass
&[x-placement^='top'] {
      margin-bottom: #{$--tooltip-arrow-size   6px};
    }
```

生成

``` css
.el-tooltip__popper[x-placement^=top]{margin-bottom:calc(var(--el-tooltip-arrow-size   6px))}
```

迁移至 css 变量过程中或许触发相关错误的生成

### What is Expected?
``` css
.el-tooltip__popper[x-placement^=top]{margin-bottom:calc(var(--el-tooltip-arrow-size)   6px)}
```

### What is actually happening?
``` css
.el-tooltip__popper[x-placement^=top]{margin-bottom:calc(var(--el-tooltip-arrow-size   6px))}
```
