### ISSUE TITLE
[Bug Report] Timeline type attribute ignored

### ISSUE THREAD

**Issue by lights0123** [element-plus/element-plus#2918]
### Element Plus version
1.0.2-beta.70

### OS/Browsers version
Chrome, Firefox

### Vue version
3.2.2

### Reproduction Link
https://jsfiddle.net/0gjx871y/

### Steps to reproduce
Add an `<el-timeline-item>` item within `<el-timeline>`, and specify a `type` attribute other than `info`.

### What is Expected?
The circles on the left should be light gray by default, and then overridden when specifying a `type`. This is [how it worked in Element UI](https://element.eleme.io/#/en-US/component/timeline), as well as Element Plus until a recent regression (since beta-54). This is a quick fix to revert to the correct behavior:

```scss
@use "sass:map";
@import "~element-plus/packages/theme-chalk/src/common/var.scss";
.el-timeline-item__node {
	background-color: var(--el-timeline-node-color) !important;
}

@each $type in $--types {
	.el-timeline-item__node.el-timeline-item__node--#{$type} {
		background-color: map.get($--colors, $type, 'base') !important;
	}
}
```

### What is actually happening?
Every circle is dark gray, as if `type="info"` was set.
