### ISSUE TITLE
[bug report] overwriting the subject SCSS variable does not take effect

### ISSUE THREAD

**Issue by 634323580** [element-plus/element-plus#3588]
### Element Plus version
1.1.0-beta.15

### OS/Browsers version
windows10 / chrome 93.0.4577.82

### Vue version
3.2.14

### Reproduction Link
https://codesandbox.io/embed/compassionate-villani-8fj98?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce
https://codesandbox.io/embed/compassionate-villani-8fj98?fontsize=14&hidenavigation=1&theme=dark

### What is Expected?
正确覆盖scss变量

### What is actually happening?
没有任何效果

**Comment by xhuz** [comment]
```sass
// element-variables.scss
@use '~element-plus/theme-chalk/src/index.scss' with
  (
    $--font-path: '~element-plus/theme-chalk/src/fonts',
    $--colors: (
      'primary': (
        'base': green,
      ),
    )
  );

```
```ts
// main.ts
import './themes/element-variables.scss';
```

**Comment by msidolphin** [comment]
Try this?
```scss
@import './var.scss';
@import 'element-plus/theme-chalk/src/index.scss';
```

**Comment by jlzm** [comment]
- vite: 2.5.10
- vue: 3.2.12
- element-plus: 1.1.0-beta.15

Not effect on all
```scss
// file
.custom-class {
    $--colors: (
	'primary': (
		'base': pink;
	)
    );
}

@import 'element-plus/theme-chalk/src/index.scss';
```

Not effect on el-button (no test other component)
```scss
// file
.custom-class {
    --el-color-primary: pink;
}

@import 'element-plus/theme-chalk/src/index.scss';
```

Effect on all
```scss
// file
$--colors: (
    'primary': (
	'base': pink;
    )
);

@import 'element-plus/theme-chalk/src/index.scss';
```
