### ISSUE TITLE
[Bug Report] How to override style of component

### ISSUE THREAD

**Issue by 1sm23** [element-plus/element-plus#4825]
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Windows 10 Chrome 96

### Vue version
3.2.26

### Reproduction Link
https://gist.github.com/1sm23/4ff067c26dd84a2d248bd73ddad4f436

### Steps to reproduce
我想覆盖组件 `el-cascader` 的样式，直接在页面上这样写不起作用
I want to override style of component el-cascader , this does not work.
```css
  :deep(.el-cascader-panel) {
    .el-checkbox {
      display: none;
    }
  }
```
于是我想修改scss变量
then I modify scss variables 
文件 checkbox.scss
file checkbox.scss
```scss
@include b(checkbox) {
  color: var(--el-checkbox-text-color);
  font-weight: var(--el-checkbox-font-weight);
  font-size: var(--el-font-size-base);
  position: relative;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  height: map.get($checkbox-height, 'default');
}
```
像上面的 `height ` 我可以通过修改 `$checkbox-height` 来修改，但是怎么修改 `display` 这种是固定的样式，scss 有什么覆盖的语法吗
Like the `height ` above, I can modify it by modifying `$checkbox-height` , but how can I modify the `display`
```scss
@forward "element-plus/theme-chalk/src/common/var.scss" with (
  $colors: (
    "primary": (
      "base": #178EE7,
    ),
  ),
  $checkbox-height:(
   "fake-style": 40px,
  ),
);
```
### What is Expected?
Override style of component

### What is actually happening?
Did not work
```css
  :deep(.el-cascader-panel) {
    .el-checkbox {
      display: none;
    }
  }
```
