### ISSUE TITLE
[Bug Report] el-select 中  size="small"  multiple=true  filterable=true 选择选中后高度会变为34px （不选中则正常）

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5143]
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
win11  /  Microsoft Edge 最新版

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/mxp131011/pen/wvrXMob?editors=1100

### Steps to reproduce
` <el-select   multiple filterable  size="small">`  即：多选且可搜索时当选中某一项或几项时，会导致选择框变大

原因是 `.el-select.el-select--small > .el-select.el-select--small > .el-select__tags > .el-select__input.is-small` 的`height` 为 `28px` 所以导致 `el-select`  被撑开

临时解决方式：

```css
.el-select.el-select--small{
    .select-trigger{
        .el-select__tags{
            .el-select__input.is-small{
                height: 22px; 
            }
        }
    }
}
```

### What is Expected?
选中后  ` <el-select   multiple filterable  size="small">`  高度为24px

### What is actually happening?
 选中后 ` <el-select   multiple filterable  size="small">`  高度为34px
