### ISSUE TITLE
[Bug Report] How do I modify the filtered table header icon?

### ISSUE THREAD

**Issue by zhoufanglu** [element-plus/element-plus#5381]
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
96.0.4664.110

### Vue version
3.2.26

### Steps to reproduce
I want to change filter icon, how?
![image](https://user-images.githubusercontent.com/24451091/149445274-2bd43839-0532-473e-aca0-b75666c78163.png)
The way I want it to look
![image](https://user-images.githubusercontent.com/24451091/149445343-c4ea2938-0230-4075-b0d5-90fd0c931e76.png)
how to implementation?

**Comment by 617769571** [comment]
Hello, have you solved it now?

**Comment by wjw020206** [comment]
You can use the following code
```css
:deep(.el-table__column-filter-trigger) {
   & > .el-icon {
     @apply hidden;
   }
   &::after {
     content: '';
     @apply block w-[16px] h-[16px];
     background: url(@/assets/images/demo.png) no-repeat;
     background-size: cover;
   }
}
```
