### ISSUE TITLE
[Feature Request] `el-menu` 增加 `size` 或者 `height` 属性

### ISSUE THREAD

**Issue by mxp131011** [element-plus/element-plus#5585]
### Existing Component
是

### Component Name
`el-menu`

### Description
希望 `el-menu` 增加 `size` 属性 当侧边栏的菜单太多时现在的默认高度，太高了希望增加size属性或者height属性控制每条item的高度

**Comment by mxp131011** [comment]
临时解决方式：设置css 样式
```css
 :deep(.el-menu) {
                    $menu-height: 42px;
                    .el-menu-item {
                        height: $menu-height;
                        line-height: $menu-height;
                    }
                    .el-sub-menu {
                        .el-sub-menu__title {
                            height: $menu-height;
                            line-height: $menu-height;
                        }
                    }
                }

```

**Comment by mxp131011** [comment]
临时解决方式：设置css 样式
```css
 :deep(.el-menu) {
                    $menu-height: 42px;
                    .el-menu-item {
                        height: $menu-height;
                        line-height: $menu-height;
                    }
                    .el-sub-menu {
                        .el-sub-menu__title {
                            height: $menu-height;
                            line-height: $menu-height;
                        }
                    }
                }

```
