### ISSUE TITLE
[Bug Report] [Component] [input-number] Number text in `<el-input-number>` with `controls-position=right` is not centered

### ISSUE THREAD

**Issue by CarterLi** [element-plus/element-plus#7215]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `Chrome 100.0.4896.127 / macOS 12.3`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/input-number.html#%E6%8C%89%E9%92%AE%E4%BD%8D%E7%BD%AE)

### Steps to reproduce

```html
  <el-input-number
    v-model="num"
    class="mx-4"
    :min="1"
    :max="10"
    controls-position="right"
  />
```

<img width="644" alt="image" src="https://user-images.githubusercontent.com/6134068/163754398-aa007a5b-a851-4da9-ad23-af37cd48f6ab.png">

### What is Expected?

数字居中显示

### What is actually happening?

数字没有居中

### Additional comments

el-input-number里的el-input还有个11px的蜜汁左内边距，不知道为啥要加这个

**Comment by CarterLi** [comment]
暂时hack解决了


```scss
.el-input-number.is-controls-right {
  .el-input__inner {
    padding-right: 35px !important;
    padding-left: 0 !important;
  }
}
```
