### ISSUE TITLE
[Bug Report] [Style] [input] el-input聚焦后鼠标离开输入框导致边框高亮

### ISSUE THREAD

**Issue by jackjtr** [element-plus/element-plus#7391]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome 100.0.4896.127`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Link]()

### Steps to reproduce

使用场景需要隐藏边框，通过以下代码覆盖默认样式后，鼠标点击输入框，移出输入框范围后边框出现，由于默认样式难以定位问题，请教一下如何调整
```css
.el-input__wrapper {
  box-shadow: none;
  border: none;
  background: transparent;

  &:focus,
  &:hover {
    box-shadow: none;
    border: none;
  }
}
```

### What is Expected?

清除输入框所有状态下边框样式

### What is actually happening?

鼠标点击输入框，移出输入框范围后边框出现

### Additional comments

playground无法修改el-input样式，CodeSandbox环境vue 3.2.33 element-plus 2.1.11 运行报错
