### ISSUE TITLE
[Feature Request] [Enhancement] [button] Add `link` prop

### ISSUE THREAD

**Issue by ModyQyW** [element-plus/element-plus#7610]
Feature type: **`Enhancement`**

## Details

- Enhanced compone nt name: `button`

## Description

The original website quote is as follows.

> Text button has been upgraded with a new design since 2.2.0 , if you want to use the previous version like button, you might want to check `Link` out.

However, the `Link` component is not exactly the same as the previous text button.

- When using multiple `Link` components, you need to add `margin` manually or use `Space` components to ensure the spacing. When using multiple `Button` components, the spacing is already set and does not need to be handled manually.
- The hover, focus, and active states of the `Link` component are all styled differently from the previous text buttons, including text color, underline, etc.
- The `Link` component renders the `<a>` tag and the `Button` component renders the `<button>` tag.

I think these differences make it impossible to use the `Link` component directly to replace the previous text button in practice. Is it possible to consider adding a `link` property to the `Button` component that corresponds to the previous text button style?

官网原话如下。

> Text button has been upgraded with a new design since 2.2.0 , if you want to use the previous version like button, you might want to check `Link` out.

但是，`Link` 组件和之前的文字按钮并不完全相同。

- 使用多个 `Link` 组件时，需要手动增加 `margin` 或使用 `Space` 组件以保证间距。使用多个 `Button` 组件时，间距已经设置好了，不需要手动处理。
- `Link` 组件的 hover、focus、active 状态下的样式都与之前的文字按钮有所差异，包括文字颜色、下划线等。
- `Link` 组件渲染出 `<a>` 标签，`Button` 组件渲染出 `<button>` 标签。

我认为，这些差异使得实际开发中无法直接使用 `Link` 组件替换之前的文字按钮。是否可以考虑为 `Button` 组件增加 `link` 属性并对应到之前的文字按钮样式？

### Additional comments

EDIT: The original idea of the issue comes from [Ant Design Button](https://ant.design/components/button/) BTW.

**Comment by mxp131011** [comment]
我是觉得也是有必要的，或者是否可以考虑在focus，active，hover和disabled 时高亮一下文本颜色,
现在想改回原来的样式大概需要如下：

```scss 
.el-button.is-text {
    padding: 5px; // 原始边距为 padding:  5px 11px;
    background: none; // 禁用背景

   //  上面background 加 !important; 则可以不用写下面一段
    &:focus,
    &:active,
    &:hover,
    &:not(.is-disabled):focus,
    &:not(.is-disabled):active,
    &:not(.is-disabled):hover {
        background: none; // 禁用背景
    }

    // 设置选中或禁止的文本颜色  （因为是循环添加所以打包后会生产大量css样式）如官方默认就修改了颜色就不用写循环了可节省代码体积
    &.el-button-- {
        // 循环添加文字颜色高亮
        @each $item in 'primary', 'success', 'warning', 'danger', 'error', 'info' {
            &#{$item}:not(.is-disabled):focus,
            &#{$item}:not(.is-disabled):active,
            &#{$item}:not(.is-disabled):hover {
                color: var(--el-color-#{$item}-light-3);
            }

            &#{$item}.is-disabled,
            &#{$item}.is-disabled:hover,
            &#{$item}.is-disabled:focus,
            &#{$item}.is-disabled:active {
                color: var(--el-color-#{$item}-light-5);
            }
        }
    }
}

```

建议要么就添加一个type="link",要么就在focus，active，hover和disabled 时高亮一下文本颜色，这样改动最小
