### ISSUE TITLE
[Component] [tree-v2] el-tree-v2无法横向滚动的问题

### ISSUE THREAD

**Issue by Jkanon** [element-plus/element-plus#9861]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.17`
- Browser / OS: `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree-v2`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/tree-v2.html)

### Steps to reproduce

建议增加一个参数来支持横向滚动，当需要横向滚动时，将渲染的节点同时以relative的方式进行隐式渲染占位以触发横向滚动

### What is Expected?

超出容器宽度，自动横向滚动

### What is actually happening?

无法横向滚动

### Additional comments

_(empty)_

**Comment by wangxiaohuiboy** [comment]
这个问题官方解决了吗，楼主有什么方式处理的？

**Comment by moliu666** [comment]
这个问题官方仍没有进展，不知道遇到这个问题的同学是怎么处理的，希望得到回复

**Comment by Gszekt** [comment]
我也遇到同样的问题了，有解决方案吗？

**Comment by GuShiLongSkr** [comment]
请问有好的解决方案吗 望告知

**Comment by viulu5824** [comment]
如果给.el-tree-node__children 的{overflow:hidden}覆盖为{overflow:visible !important}，能出现横向滚动条。但是会出现节点展示动画溢出的问题，所以现在很矛盾

**Comment by wyx1300379707** [comment]
外围套一层div
 :deep(.el-vl__window){
        overflow: inherit !important;
      }

**Comment by kong-cheng159** [comment]
> 外围套层div :deep(.el-vl__window){ 故障:继承！ }

这个方案会导致出现两个滚动条且滚动数据消失

**Comment by fengshucheng** [comment]
[inactive](https://github.com/element-plus/element-plus/labels/inactive) 意思是修复好了吗?
目前可以使用 .el-vl__window{scrollbar-width: thin;} 将横向滚动条显示出来!

**Comment by fengshucheng** [comment]
可以看看这个是一种解决方案
https://wsqjsygft.blog.csdn.net/article/details/142463178?spm=1001.2014.3001.5502

**Comment by ZiHan-code** [comment]
可以参考一下这个，主要是重写el-tree的display样式
https://guoshengbo.github.io/2019/02/28/%E8%A7%A3%E5%86%B3Element-ui-Tree%E7%BB%84%E4%BB%B6%E6%97%A0%E6%B3%95%E5%87%BA%E7%8E%B0%E6%A8%AA%E5%90%91%E6%BB%9A%E5%8A%A8%E6%9D%A1/

**Comment by ae86yyk** [comment]
```css
.el-vl__window {
  overflow-y: hidden !important;
  scrollbar-width: inherit;
}

.el-vl__window::-webkit-scrollbar-track {
  background-color: transparent;
  border-radius: 4px;
}

.el-vl__window::-webkit-scrollbar-thumb {
  background: #d6d6d6;
  border-radius: 4px;
}

.el-vl__window::-webkit-scrollbar-thumb:hover {
  background: #9f9f9f;
}

.el-vl__window::-webkit-scrollbar {
  display: unset;
  height: 8px;
}
```
